### ISSUE TITLE
Recommended procedure to reupload jobs

### ISSUE THREAD

**Issue by andrea-begnoni** [jmd-dk/Nbody#13]
Hi,

I would like to ask what is the recommended procedure to reupload jobs when the simulation lasts more than the wall time in slurm. I use a slightly modified script generated on a remote cluster by concept and I launch the job using `sbatch` . 

Right now I am doing a rough estimate of the redshift the simulation will reach in a wall-time, I save a snapshot at that point, stop the simulation and I use it as initial condition of the new simulation.

Is there an automatic way of doing it? Or any recommendation for a more efficient procedure.

Thanks in advance.

**Comment by jmd-dk** [comment]
What you are currently doing sounds okay to me. There is a system in-place for doing this automatically, but I don't think it has been used a lot, so it might be flaky. If you try it out I would be happy to hear if it works for you.

Try setting the [`autosave_interval`](https://jmd-dk.github.io/concept/parameters/input_output.html#autosave-interval) parameter to some reasonable value, e.g. 10% of the allowed wall-time. The simulation will then dump an "autosave" snapshot every so often, along with an `auxiliary` file containing time-step information. When auto-saving a second time, the auto-saved files will be overwritten, so it's not costly in disk space to set `autosave_interval` to a low value. As saving to disk takes time, though, setting `autosave_interval` too low is not a good idea.

When re-running the simulation a second (or third, ...) time using the original, unmodified parameter file, the simulation will begin from the last autosave.

As described in the [docs](https://jmd-dk.github.io/concept/parameters/input_output.html#autosave-interval), the autosaved files will be placed in accordance with `output_dirs['autosave']`, which defaults to `ic/autosave`. Subdirectories are created with names according to the parameter file, so autosaves from different simulations should not overwrite each other.

**Comment by andrea-begnoni** [comment]
Thank you very much!

I used it with success in the past weeks and it is working well. 
I find that for large simulations (N=4096^3) the time interval is not accurate but I believe it is linked to the time to write and read the snapshot.

For example, I set it to `10 hrs` and the first file was saved almost 14 hrs after the job started. 
Apart from that it works nicely, thanks.
